
source 'https://github.com/pengwenxin/CGSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CGSpecialKit_Category_Example' do
  pod 'CGSpecialKit_Category', :path => '../'

  target 'CGSpecialKit_Category_Tests' do
    inherit! :search_paths

    
  end
end
